"""Merge the manuscript into one self-contained LaTeX file: nitsci_paper_combined.tex

- inlines every sections/*.tex file (\\input) in place;
- sections flow continuously (no page break before each section);
- inlines the generated results.tex, so every number is in the one file;
- embeds the bibliography (from the .bbl that bibtex produces), so the file
  compiles with pdflatex alone.  refs.bib is kept for journals that want it.

Run after ./make_section_pdfs.sh (which produces results.tex and the .bbl):
    python make_combined.py
    pdflatex nitsci_paper_combined && pdflatex nitsci_paper_combined
"""
import os
import re
import subprocess

HERE = os.path.dirname(os.path.abspath(__file__))


def read(name):
    with open(os.path.join(HERE, name)) as f:
        return f.read()


def main():
    if not os.path.exists(os.path.join(HERE, 'nitsci_paper.bbl')):
        subprocess.run(['python3', 'fill_results.py'], cwd=HERE, check=True)
        for cmd in (['pdflatex', '-interaction=nonstopmode', 'nitsci_paper'], ['bibtex', 'nitsci_paper']):
            subprocess.run(cmd, cwd=HERE, stdout=subprocess.DEVNULL, check=False)
    src = read('nitsci_paper.tex')

    # continuous sections, inline section files
    src = src.replace(r'\newif\ifsectionsonnewpages\sectionsonnewpagestrue',
                      r'\newif\ifsectionsonnewpages\sectionsonnewpagesfalse')
    src = re.sub(r'\\input\{(sections/[^}]+)\}',
                 lambda m: '\n% ---------------- ' + m.group(1) + '.tex ----------------\n'
                 + read(m.group(1) + '.tex').strip() + '\n', src)
    src = src.replace('% Each section lives in its own file under sections/. With \\sectionsonnewpages\n'
                      '% every section starts on a new page (set \\sectionsonnewpagesfalse for submission).\n', '')

    # inline the result values
    res = read('results.tex') if os.path.exists(os.path.join(HERE, 'results.tex')) else '% (no results yet)\n'
    src = src.replace(r'\InputIfFileExists{results.tex}{}{}', '% ---- result values (from fill_results.py) ----\n' + res)

    # embed the bibliography
    bbl = read('nitsci_paper.bbl')
    src = src.replace('\\bibliographystyle{unsrtnat}\n\\bibliography{refs}', bbl.strip())

    src = src.replace('%  NITSCI: manuscript', '%  NITSCI: complete manuscript in one file (generated by make_combined.py)')
    with open(os.path.join(HERE, 'nitsci_paper_combined.tex'), 'w') as f:
        f.write(src)
    print('wrote nitsci_paper_combined.tex')


if __name__ == '__main__':
    main()
